# Generated by Django 3.0.7 on 2020-10-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coll_user_name', models.CharField(default='01', max_length=128)),
                ('coll_film_title', models.CharField(default='坏孩子的秋天', max_length=128)),
                ('coll_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_content_str', models.TextField(max_length=2560)),
                ('c_user_name', models.CharField(default='01', max_length=128)),
                ('c_film_title', models.CharField(default='坏孩子的秋天', max_length=128)),
                ('com_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl_title_str', models.TextField()),
                ('fl_type_str', models.TextField(blank=True, null=0)),
                ('fl_data_str', models.TextField(blank=True, null=0)),
                ('fl_mainRole_str', models.TextField(blank=True, null=0)),
                ('fl_anotherName_str', models.TextField(blank=True, null=0)),
                ('fl_director_str', models.TextField(blank=True, null=0)),
                ('fl_scenarist_str', models.TextField(blank=True, null=0)),
                ('fl_length_str', models.CharField(blank=True, max_length=128, null=0)),
                ('fl_language_str', models.TextField(blank=True, null=0)),
                ('fl_commentNum', models.CharField(blank=True, default='500', max_length=128)),
                ('fl_replyNum', models.CharField(blank=True, max_length=128, null=0)),
                ('fl_grade', models.CharField(blank=True, default='5.6', max_length=128)),
                ('fl_id_poster', models.CharField(default='miss_h', max_length=128)),
                ('fl_country', models.CharField(blank=True, max_length=128, null=0)),
                ('fl_url_d', models.CharField(blank=True, max_length=128, null=0)),
                ('fl_url_i', models.CharField(blank=True, max_length=128, null=0)),
                ('fl_intro', models.TextField(default='暂时没有简介')),
            ],
        ),
        migrations.CreateModel(
            name='FilmTag_f',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ft_title', models.TextField(max_length=2560)),
                ('ft_tag', models.CharField(blank=True, max_length=128, null=0)),
            ],
        ),
        migrations.CreateModel(
            name='Score_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_score_str', models.CharField(default='5.6', max_length=32)),
                ('s_user_name', models.CharField(default='01', max_length=128)),
                ('s_film_title', models.CharField(default='坏孩子的秋天', max_length=128)),
                ('score_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=32)),
                ('user_personal', models.CharField(default='当前显示为默认标签，您可以点击右方修改进行修改', max_length=100)),
                ('user_movie_tag', models.CharField(choices=[('terrify', '惊悚'), ('action', '动作'), ('love', '爱情'), ('adventure', '冒险'), ('western', '欧美'), ('funny', '搞笑'), ('japan_and_korea', '日韩'), ('crime', '犯罪'), ('disaster', '灾难')], default=' ', max_length=100)),
                ('user_pic', models.CharField(default='/static/images/userPic.jpg', max_length=100)),
                ('c_time', models.DateTimeField(auto_now=True)),
                ('user_address', models.CharField(default='当前显示为默认地址，您可以点击右方修改进行修改', max_length=100)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
