# Generated by Django 3.0.7 on 2020-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='fl_id_poster',
            field=models.TextField(default='miss_h', max_length=128),
        ),
    ]
